defmodule RivetFabric.Adapters.Quadlet do
  @moduledoc """
  Substrate adapter backed by podman and systemd quadlets.

  Each node becomes a `.container` unit under
  `~/.config/containers/systemd/`, which the podman user generator turns into a
  systemd service on `daemon-reload`. This is the local test path: it exercises
  the same address-discovery and bootstrap ordering as Fly without provisioning
  anything billable.

  Rootless podman is assumed. Containers share a user network, so peers reach
  each other by container name and by IP, which is what FoundationDB needs.
  """

  @behaviour RivetFabric.Ports.Substrate

  alias RivetFabric.Shell

  @unit_dir Path.expand("~/.config/containers/systemd")

  def unit_dir, do: @unit_dir

  defp unit_name(app, name), do: "#{app}--#{name}"
  defp unit_path(app, name), do: Path.join(@unit_dir, "#{unit_name(app, name)}.container")
  defp service(app, name), do: "#{unit_name(app, name)}.service"

  @impl true
  def network_ensure(net) do
    case Shell.run("podman", ["network", "exists", net]) do
      {_, 0} ->
        :ok

      _ ->
        case Shell.run("podman", ["network", "create", net]) do
          {_, 0} -> :ok
          {out, code} -> {:error, "network create failed (#{code}): #{tail(out)}"}
        end
    end
  end

  @impl true
  def image_ensure(%{tag: tag, containerfile: containerfile, context: context} = spec) do
    args =
      ["build", "-t", tag, "-f", containerfile] ++
        Enum.flat_map(Map.get(spec, :build_args, %{}), fn {k, v} ->
          ["--build-arg", "#{k}=#{v}"]
        end) ++ [context]

    case Shell.run("podman", args, timeout: :timer.minutes(60)) do
      {_, 0} -> {:ok, tag}
      {out, code} -> {:error, "podman build failed (#{code}): #{tail(out)}"}
    end
  end

  @impl true
  def node_ensure(spec) do
    File.mkdir_p!(@unit_dir)
    File.write!(unit_path(spec.app, spec.name), render_unit(spec))

    with :ok <- apply(),
         :ok <- start_service(spec.app, spec.name) do
      :ok
    end
  end

  @doc """
  Render a `.container` quadlet unit.

  Exposed so tests can assert on the generated unit without podman present.
  """
  def render_unit(spec) do
    env =
      spec
      |> Map.get(:env, %{})
      |> Enum.sort()
      |> Enum.map(fn {k, v} -> "Environment=#{k}=#{v}" end)

    publish =
      spec
      |> Map.get(:publish, [])
      |> Enum.map(fn {host, guest} -> "PublishPort=#{host}:#{guest}" end)

    volume =
      case Map.get(spec, :volume) do
        {vol, mount} -> ["Volume=#{vol}:#{mount}"]
        _ -> []
      end

    network =
      case Map.get(spec, :network) do
        nil -> []
        net -> ["Network=#{net}"]
      end

    command =
      case Map.get(spec, :command) do
        nil -> []
        [] -> []
        argv -> ["Exec=" <> Enum.join(argv, " ")]
      end

    lines =
      [
        "# Generated by rivet-fabric-ports-adapters. Do not edit by hand.",
        "[Unit]",
        "Description=#{spec.app} #{spec.name}",
        "",
        "[Container]",
        "ContainerName=#{unit_name(spec.app, spec.name)}",
        "Image=#{spec.image}"
      ] ++
        network ++
        volume ++
        publish ++
        env ++
        command ++
        [
          "",
          "[Service]",
          "Restart=always",
          "",
          "[Install]",
          "WantedBy=default.target"
        ]

    Enum.join(lines, "\n") <> "\n"
  end

  @impl true
  def apply do
    case Shell.run("systemctl", ["--user", "daemon-reload"]) do
      {_, 0} -> :ok
      {out, code} -> {:error, "daemon-reload failed (#{code}): #{tail(out)}"}
    end
  end

  defp start_service(app, name) do
    case Shell.run("systemctl", ["--user", "start", service(app, name)],
           timeout: :timer.minutes(5)
         ) do
      {_, 0} -> :ok
      {out, code} -> {:error, "start #{service(app, name)} failed (#{code}): #{tail(out)}"}
    end
  end

  @impl true
  def node_list(app) do
    {out, code} =
      Shell.run("podman", [
        "ps",
        "--all",
        "--filter",
        "name=#{app}--",
        "--format",
        "{{.Names}}\t{{.State}}"
      ])

    if code != 0 do
      {:error, "podman ps failed: #{tail(out)}"}
    else
      nodes =
        out
        |> String.split("\n", trim: true)
        |> Enum.map(fn line ->
          [container, state] = String.split(line, "\t", parts: 2)

          %{
            name: String.replace_prefix(container, "#{app}--", ""),
            address: inspect_address(container),
            state: normalize_state(state)
          }
        end)
        |> Enum.sort_by(& &1.name)

      {:ok, nodes}
    end
  end

  defp normalize_state(state) do
    case String.downcase(String.trim(state)) do
      "running" -> :started
      "exited" -> :stopped
      "created" -> :stopped
      other -> String.to_atom(other)
    end
  end

  defp inspect_address(container) do
    fmt = "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"

    case Shell.run("podman", ["inspect", "-f", fmt, container]) do
      {out, 0} ->
        case String.trim(out) do
          "" -> nil
          ip -> ip
        end

      _ ->
        nil
    end
  end

  @impl true
  def node_exec(app, name, argv) do
    case Shell.run("podman", ["exec", unit_name(app, name)] ++ argv, timeout: :timer.minutes(5)) do
      {out, 0} -> {:ok, out}
      {out, code} -> {:error, "exec failed (#{code}): #{tail(out)}"}
    end
  end

  @impl true
  def node_write_file(app, name, guest_path, content) do
    tmp = Path.join(System.tmp_dir!(), "rivet-fabric-#{:erlang.unique_integer([:positive])}")
    File.write!(tmp, content)

    dir = Path.dirname(guest_path)
    _ = node_exec(app, name, ["mkdir", "-p", dir])

    result =
      case Shell.run("podman", ["cp", tmp, "#{unit_name(app, name)}:#{guest_path}"]) do
        {_, 0} -> :ok
        {out, code} -> {:error, "cp failed (#{code}): #{tail(out)}"}
      end

    File.rm(tmp)
    result
  end

  @impl true
  def node_stop(app, name) do
    case Shell.run("systemctl", ["--user", "stop", service(app, name)],
           timeout: :timer.minutes(2)
         ) do
      {_, 0} -> :ok
      {out, code} -> {:error, "stop failed (#{code}): #{tail(out)}"}
    end
  end

  @impl true
  def node_destroy(app, name) do
    _ = node_stop(app, name)
    path = unit_path(app, name)
    if File.exists?(path), do: File.rm!(path)
    _ = Shell.run("podman", ["rm", "-f", unit_name(app, name)])
    apply()
  end

  defp tail(out) do
    out |> String.split("\n") |> Enum.take(-12) |> Enum.join("\n")
  end
end
